stateDiagram-v2
    [*] --> ASSIGNED
    ASSIGNED --> STARTED
    STARTED --> WAITING
    WAITING --> STARTED
    STARTED --> COMPLETED_SUCCESS
    STARTED --> COMPLETED_ERROR
    COMPLETED_SUCCESS --> [*]
    COMPLETED_ERROR --> [*]
